# =====================================================================
# Nirmana-Shell - Oh-My-Posh Port: Atomic Theme
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$bun\
$dart\
$nodejs\
$python\
$package\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #FF9248) "
error_symbol = "[❯](bold #ef5350) "

[directory]
format = "[](fg:#FF9248)[ $path ](bg:#FF9248 fg:#2d3436)[](fg:#FF9248 bg:#FFFB38)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[  $branch](bg:#FFFB38 fg:#011627)"

[git_status]
format = "[$all_status$ahead_behind](bg:#FFFB38 fg:#011627)[](fg:#FFFB38) "
style = "bg:#FFFB38 fg:#011627"
conflicted = " 󰞇"
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
untracked = " ?"
stashed = " "
modified = " !"
staged = " +"
renamed = " »"
deleted = " ✘"

[bun]
format = "[](fg:#303030)[ $version](bg:#303030 fg:#FF9F43)[](fg:#303030) "
version_format = "v${raw}"

[dart]
symbol = " "
format = "[](fg:#306998)[$symbol$version](bg:#306998 fg:#ffffff)[](fg:#306998) "
version_format = "v${raw}"

[nodejs]
symbol = "󰎙 "
format = "[](fg:#303030)[$symbol$version](bg:#303030 fg:#3C873A)[](fg:#303030) "
version_format = "v${raw}"

[python]
symbol = "󰌠 "
format = "[](fg:#306998)[$symbol$version](bg:#306998 fg:#FFE873)[](fg:#306998) "
version_format = "v${raw}"

[package]
symbol = "󰏗 "
format = "[](fg:#83769c)[$symbol$version](bg:#83769c fg:#ffffff)[](fg:#83769c) "
version_format = "v${raw}"
disabled = false

[cmd_duration]
min_time = 2_000
format = "[](fg:#83769c)[ $duration](bg:#83769c fg:#ffffff)[](fg:#83769c) "
