# =====================================================================
# Nirmana-Shell - Oh-My-Posh Port: Bubbles Theme
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$bun\
$dart\
$nodejs\
$python\
$package\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #43CCEA) "
error_symbol = "[❯](bold #E64747) "

[directory]
format = "[](fg:#29315A)[ $path](bg:#29315A fg:#3EC669)[](fg:#29315A) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#29315A)[ $branch](bg:#29315A fg:#43CCEA)"

[git_status]
format = "[$all_status$ahead_behind](bg:#29315A fg:#43CCEA)[](fg:#29315A) "
style = "bg:#29315A fg:#43CCEA"
conflicted = " 󰞇"
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
untracked = " ?"
stashed = " "
modified = " !"
staged = " +"
renamed = " »"
deleted = " ✘"

[bun]
format = "[](fg:#29315A)[ $version](bg:#29315A fg:#FF9F43)[](fg:#29315A) "
version_format = "v${raw}"

[dart]
symbol = " "
format = "[](fg:#29315A)[$symbol$version](bg:#29315A fg:#7FD5EA)[](fg:#29315A) "
version_format = "v${raw}"

[nodejs]
symbol = "󰎙 "
format = "[](fg:#29315A)[$symbol$version](bg:#29315A fg:#42E66C)[](fg:#29315A) "
version_format = "v${raw}"

[python]
symbol = "󰌠 "
format = "[](fg:#29315A)[$symbol$version](bg:#29315A fg:#E4F34A)[](fg:#29315A) "
version_format = "v${raw}"

[package]
symbol = "󰏗 "
format = "[](fg:#29315A)[$symbol$version](bg:#29315A fg:#AEA4BF)[](fg:#29315A) "
version_format = "v${raw}"
disabled = false

[cmd_duration]
min_time = 2_000
format = "[](fg:#29315A)[ $duration](bg:#29315A fg:#AEA4BF)[](fg:#29315A) "
