# =====================================================================
# Nirmana-Shell - Transpiled Theme: 1_shell
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$username\
$time\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$memory_usage\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[username]
format = "[$user](fg:#ffbebc) "
show_always = true

[time]
format = "[ $time](fg:#bc93ff) "
disabled = false
time_format = "%A at %I:%M %p"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#ee79d1) "

[cmd_duration]
format = "[  $duration ](fg:#a9ffb4)"

[memory_usage]
format = "[ 󰍛 $ram_pct ](fg:#94ffa2)"

[character]
success_symbol = "[ ](bold #A9FFB4) "
error_symbol = "[ ](bold #ef5350) "
