# =====================================================================
# Nirmana-Shell - Transpiled Theme: agnoster
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$sudo\
$username\
$directory\
$git_branch\
$git_status\
$python\
$character\
"""

[character]
format = "[](fg:prev_bg) "
success_symbol = ""
error_symbol = ""

[sudo]
style = "fg:#100e23 bg:#ffe9aa"
format = "[  ]($style)[](fg:#ffe9aa bg:#ffffff)"
disabled = false

[username]
format = "[ $user ](fg:#100e23 bg:#ffffff)"
show_always = true

[directory]
format = "[](fg:prev_bg bg:#91ddff)[ $path ](fg:#100e23 bg:#91ddff)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:prev_bg bg:#95ffa4)[  $branch ](fg:#193549 bg:#95ffa4)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#193549 bg:#95ffa4))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[python]
format = "[](fg:prev_bg bg:#906cff)[ 󰌠 $version ](fg:#100e23 bg:#906cff)"
