# =====================================================================
# Nirmana-Shell - Transpiled Theme: agnoster.minimal
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$character\
"""

[username]
format = "[$user](fg:#ffffff) "
show_always = true

[directory]
format = "[  $path ](fg:#ffffff bg:#007ACC)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#ffffff bg:#007ACC))[](fg:#007ACC) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[  $branch](fg:#ffffff bg:#007ACC)"

[character]
success_symbol = ""
error_symbol = ""
