# =====================================================================
# Nirmana-Shell - Transpiled Theme: agnosterplus
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$character\
$fill\
$time\
"""

[fill]
symbol = " "

[username]
format = "[$user ](fg:#100e23 bg:#ffffff)"
show_always = true

[directory]
format = "[](fg:#ffffff bg:#91ddff)[  $path ](fg:#100e23 bg:#91ddff)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#193549 bg:#95ffa4))[](fg:#95ffa4) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#91ddff bg:#95ffa4)[  $branch](fg:#193549 bg:#95ffa4)"

[time]
format = "[  $time ](fg:#007ACC)"
disabled = false
time_format = "%H:%M:%S"

[character]
success_symbol = ""
error_symbol = ""
