# =====================================================================
# Nirmana-Shell - Transpiled Theme: atomicBit
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python\
$java\
$dotnet\
$golang\
$rust\
$dart\
$julia\
$ruby\
$battery\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
format = "[$user](fg:white) "
show_always = true

[directory]
format = "[ $path](fg:#ff5555) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](purple) "

[nodejs]
format = "[ 󰎙 $version ](fg:#3C873A)"

[python]
format = "[ 󰌠 $version ](fg:#FFE873)"

[java]
format = "[  $version ](fg:#ec2729)"

[dotnet]
format = "[ 󰪮 $version ](fg:#0d6da8)"

[golang]
format = "[  $version ](fg:#06aad5)"

[rust]
format = "[  $version ](fg:#925837)"

[dart]
format = "[  $version ](fg:#055b9c)"

[julia]
format = "[  $version ](fg:#359a25)"

[ruby]
format = "[  $version ](fg:#9c1006)"

[battery]
format = "[ 󰁹 $percentage ](fg:#ffffff)"
disabled = false

[time]
format = "[  $time ](fg:#55ffff)"
disabled = false
time_format = "_2,%H:%M"

[character]
success_symbol = "[ ](bold #ecf7fa) "
error_symbol = "[ ](bold #ef5350) "
