# =====================================================================
# Nirmana-Shell - Transpiled Theme: avit
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$sudo\
$line_break\
$character\
"""

[directory]
format = "[ $path](#ffffff) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $branch](#C2C206)"

[git_status]
format = "([$all_status$ahead_behind](#C2C206) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[sudo]
disabled = false
symbol = " "
format = "[ ](#B5B50D)"

[character]
success_symbol = "[❯ ](bold #C94A16) "
error_symbol = "[❯ ](bold #ef5350) "
