# =====================================================================
# Nirmana-Shell - Transpiled Theme: blue-owl
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$sudo\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$character\
$fill\
$username\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](#FFEB3B)"

[directory]
format = "[](bg:#01579B)[ $path](fg:#ffffff bg:#01579B)[](fg:#01579B) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#00C853)[ $branch](fg:#000000 bg:#00C853)"

[git_status]
format = "([$all_status$ahead_behind](fg:#000000 bg:#00C853)[](fg:#00C853) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
min_time = 1
format = "[](bg:#49404f)[ $duration](fg:#ffffff bg:#49404f)[](fg:#49404f) "

[character]
success_symbol = "[❯ ](bold #ffffff) "
error_symbol = "[❯ ](bold #ff0000) "

[username]
show_always = true
format = "[](fg:#29315A)[$user](fg:#43CCEA bg:#29315A)[](fg:#29315A) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[](fg:#29315A)[$time](fg:#3EC669 bg:#29315A) "
