# =====================================================================
# Nirmana-Shell - Transpiled Theme: bubblesline
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$username\
$character\
$fill\
$directory\
$git_branch\
$python\
$golang\
$nodejs\
$ruby\
$java\
$julia\
$battery\
"""

[fill]
symbol = " "

[directory]
format = "[](fg:#424242)[  $path ](fg:#3EC669 bg:#424242)"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[  $branch ](fg:#43CCEA bg:#424242)"

[username]
format = "[](fg:#424242)[$user ](fg:#9B6BDF bg:#424242)[](fg:#424242) "
show_always = true

[python]
format = "[ 󰌠 $version ](fg:#E4F34A bg:#424242)"

[golang]
format = "[  $version ](fg:#7FD5EA bg:#424242)"

[nodejs]
format = "[ 󰎙 $version ](fg:#42E66C bg:#424242)"

[ruby]
format = "[  $version ](fg:#E64747 bg:#424242)"

[java]
format = "[  $version ](fg:#E64747 bg:#424242)"

[julia]
format = "[  $version ](fg:#9B6BDF bg:#424242)"

[battery]
format = "[ 󰁹 $percentage ](fg:#9B6BDF bg:#424242)"
disabled = false

[character]
success_symbol = ""
error_symbol = ""
