# =====================================================================
# Nirmana-Shell - Transpiled Theme: capr4n
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$character\
$fill\
$time\
$cmd_duration\
"""

[fill]
symbol = " "

[username]
format = "[$user ](fg:#ffffff bg:#61AFEF)"
show_always = true

[directory]
format = "[](fg:#61AFEF bg:#C678DD)[  $path ](fg:#ffffff bg:#C678DD)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#193549 bg:#95ffa4))[](fg:#95ffa4) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#C678DD bg:#95ffa4)[  $branch](fg:#193549 bg:#95ffa4)"

[time]
format = "[](fg:#003543)[  $time ](fg:#ffffff bg:#003543)"
disabled = false
time_format = "%H:%M:%S"

[cmd_duration]
format = "[](fg:#83769c bg:#003543)[  $duration ](fg:#ffffff bg:#83769c)"

[character]
success_symbol = ""
error_symbol = ""
