# =====================================================================
# Nirmana-Shell - Transpiled Theme: catppuccin
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$line_break\
$character\
"""

[username]
show_always = true
format = "[](fg:#8AADF4)[ $user](fg:#494D64 bg:#8AADF4)[](fg:#8AADF4) "

[directory]
format = "[ $path](fg:#494D64 bg:#F5BDE6)[](fg:#F5BDE6) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#B7BDF8)[ $branch](fg:#494D64 bg:#B7BDF8)"

[git_status]
format = "([$all_status$ahead_behind](fg:#494D64 bg:#B7BDF8)[](fg:#B7BDF8) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
