# =====================================================================
# Nirmana-Shell - Transpiled Theme: catppuccin_macchiato
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$character\
"""

[username]
format = "[$user](fg:#8AADF4) "
show_always = true

[directory]
format = "[ $path](fg:#F5BDE6) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#B7BDF8) "

[character]
success_symbol = ""
error_symbol = ""
