# =====================================================================
# Nirmana-Shell - Transpiled Theme: cert
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$time\
$character\
"""

[username]
format = "[](fg:#E36464)[$user ](fg:#ffffff bg:#E36464)"
show_always = true

[directory]
format = "[](fg:#E36464 bg:#69F0AE)[  $path ](fg:#ffffff bg:#69F0AE)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#ffffff bg:#80DEEA))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#69F0AE bg:#80DEEA)[  $branch](fg:#ffffff bg:#80DEEA)"

[time]
format = "[](fg:#80DEEA bg:#F48FB1)[  $time ](fg:#ffffff bg:#F48FB1)[](fg:#F48FB1) "
disabled = false
time_format = "%H:%M"

[character]
success_symbol = ""
error_symbol = ""
