# =====================================================================
# Nirmana-Shell - Transpiled Theme: cinnamon
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$character\
"""

[username]
format = "[](fg:#07585c)[$user ](fg:#ffffff bg:#07585c)"
show_always = true

[directory]
format = "[](fg:#07585c bg:#3e9022)[  $path ](fg:#ffffff bg:#3e9022)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#ffffff bg:#de076f))[](fg:#de076f) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#3e9022 bg:#de076f)[  $branch](fg:#ffffff bg:#de076f)"

[character]
success_symbol = ""
error_symbol = ""
