# =====================================================================
# Nirmana-Shell - Transpiled Theme: clean-detailed
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$os\
$shell\
$memory_usage\
$cmd_duration\
$fill\
$git_branch\
$git_status\
$line_break\
[╭─](fg:#FEF5ED) \
${env_var.ADMIN}\
$directory\
$line_break\
$character\
"""

[fill]
symbol = " "

[character]
format = "[╰─](fg:#FEF5ED) $symbol"
success_symbol = ""
error_symbol = "[x ](bold #ef5350)"

[os]
disabled = false
style = "fg:#011627 bg:#FEF5ED"
format = "[](fg:#FEF5ED)[ $symbol ]($style)"

[os.symbols]
Windows = "󰕮"
Ubuntu = ""
Macos = ""
Linux = ""

[shell]
disabled = false
powershell_indicator = "pwsh"
bash_indicator = "bash"
zsh_indicator = "zsh"
style = "fg:#011627 bg:#FEF5ED"
format = "[](fg:#FEF5ED)[  $indicator ]($style)[](fg:#FEF5ED inverted) "

[memory_usage]
disabled = false
threshold = -1
style = "fg:#ffffff bg:#516BEB"
symbol = "󰍛"
format = "[](fg:#516BEB)[ 󰍛  MEM: $ram_pct | $ram ]($style)[](fg:#516BEB inverted) "

[cmd_duration]
format = "[](fg:#575656)[ $duration ](fg:#d6deeb bg:#575656)[](fg:#575656) "
min_time = 0
show_milliseconds = true

[git_branch]
style = "fg:#011627 bg:#17D7A0"
symbol = " "
format = "[](fg:#17D7A0)[  $branch]($style)"

[git_status]
style = "fg:#011627 bg:#17D7A0"
format = "([ $ahead_behind$all_status]($style))[](fg:#17D7A0) "
ahead = "↑${count} "
behind = "↓${count} "
modified = " ~${count} "
staged = " +${count} "
stashed = " ${count} "
untracked = " ${count} "

[env_var.ADMIN]
variable = "STARSHIP_IS_ADMIN"
style = "bold #ffeb95"
format = "[# ](fg:#ffeb95) "

[directory]
format = "[$path ](fg:#FEF5ED) "
truncation_length = 3
truncation_symbol = "…/"
