# =====================================================================
# Nirmana-Shell - Transpiled Theme: cloud-native-azure
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$shell\
$battery\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[](fg:#c386f1)[$user](fg:#ffffff bg:#c386f1)[](fg:#c386f1) "

[directory]
format = "[ $path](fg:#ffffff bg:#ff479c)[](fg:#ff479c) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#fffb38)[ $branch](fg:#193549 bg:#fffb38)"

[git_status]
format = "([$all_status$ahead_behind](fg:#193549 bg:#fffb38)[](fg:#fffb38) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[character]
success_symbol = "[ ](bold green) "
error_symbol = "[ ](bold #ffffff) "

[shell]
disabled = false
format = "[](fg:#0077c2)[ $indicator](fg:#ffffff bg:#0077c2)[](fg:#0077c2) "

[battery]
disabled = false
format = "[$symbol$percentage](fg:#ffffff bg:#f36943)[](fg:#f36943) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[](fg:#2e9599)[ $time](fg:#111111 bg:#2e9599)[](fg:#2e9599) "
