# =====================================================================
# Nirmana-Shell - Transpiled Theme: cobalt2
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character\
"""

[directory]
format = "[](fg:#1478DB)[ $path](fg:#000000 bg:#1478DB)[](fg:#1478DB) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](bg:#3AD900)[ $branch](fg:#000000 bg:#3AD900)"

[git_status]
format = "([$all_status$ahead_behind](fg:#000000 bg:#3AD900)[](fg:#3AD900) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
