# =====================================================================
# Nirmana-Shell - Transpiled Theme: craver
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$time\
$directory\
$git_branch\
$git_status\
$dotnet\
$cmd_duration\
$line_break\
$character\
"""

[time]
format = "[  $time ](fg:#FFBB00 bg:#242424)"
disabled = false
time_format = "%H:%M:%S"

[directory]
format = "[  $path ](fg:#33DD2D bg:#242424)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#3A86FF bg:#242424))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[  $branch](fg:#3A86FF bg:#242424)"

[dotnet]
format = "[](fg:#242424 bg:#0184bc)[ 󰪮 $version ](fg:#ffffff bg:#0184bc)"

[cmd_duration]
format = "[](fg:#0184bc bg:#8800dd)[  $duration ](fg:#ffffff bg:#8800dd)[](fg:#8800dd) "
min_time = 1

[character]
success_symbol = "[➜ ](bold #f1184c) "
error_symbol = "[➜ ](bold #ef5350) "
