# =====================================================================
# Nirmana-Shell - Transpiled Theme: darkblood
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
[┏](fg:#CB4B16)\
$username\
$git_branch\
$git_status\
${env_var.ADMIN}\
$status\
$line_break\
$directory\
$character\
"""

[character]
format = "$symbol"
success_symbol = "[> ](fg:#CB4B16)"
error_symbol = "[> ](fg:#CB4B16)"

[username]
show_always = true
format = "[\\[](fg:#CB4B16)[$user](fg:#ffffff)[\\]](fg:#CB4B16)"

[git_branch]
symbol = ""
format = "[\\[](fg:#CB4B16)[$symbol$branch](fg:#ffffff)[\\]](fg:#CB4B16)"

[git_status]
disabled = true

[env_var.ADMIN]
variable = "STARSHIP_IS_ADMIN"
format = "[\\[](fg:#CB4B16)[⚡](fg:#ffffff)[\\]](fg:#CB4B16)"

[status]
disabled = false
format = "[\\[x](fg:#CB4B16)[$symbol](fg:#ffffff)[\\]](fg:#CB4B16)"
success_symbol = "0"
symbol = "$status"

[directory]
format = "[┗\\[](fg:#CB4B16)[$path](fg:#ffffff)[\\]](fg:#CB4B16)"
truncation_length = 3
truncation_symbol = "…/"
