# =====================================================================
# Nirmana-Shell - Transpiled Theme: di4am0nd
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$fill\
$memory_usage\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
format = "[$user](fg:#FFBD00) "
show_always = true

[directory]
format = "[ $path](fg:#00C6F7) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#F62F2E) "

[nodejs]
format = "[󰎙 $version](fg:#98C379) "

[memory_usage]
format = "[ 󰍛 $ram_pct ](fg:#85C980)"

[cmd_duration]
format = "[  $duration ](fg:#ffffff)"

[character]
success_symbol = "[⮞ ](bold #FFBD00) "
error_symbol = "[⮞ ](bold #ef5350) "
