# =====================================================================
# Nirmana-Shell - Transpiled Theme: emodipt
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$time\
$directory\
$git_branch\
$git_status\
$character\
"""

[time]
format = "[ $time](fg:#E5C07B) "
disabled = false
time_format = "%H:%M:%S"

[directory]
format = "[ $path](fg:#61AFEF) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#F3C267) "

[character]
success_symbol = ""
error_symbol = ""
