# =====================================================================
# Nirmana-Shell - Transpiled Theme: emodipt-extend
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$time\
$shell\
$git_branch\
$git_status\
$fill\
$character\
$cmd_duration\
$line_break\
$directory\
$sudo\
$character\
"""

[fill]
symbol = " "

[time]
disabled = false
time_format = "%H:%M"
format = "[ $time](#E5C07B) "

[shell]
format = "[ $indicator](#E06C75) "

[git_branch]
format = "[ $branch](#F3C267)"

[git_status]
format = "([$all_status$ahead_behind](#F3C267) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[character]
success_symbol = "[❯ ](bold #b8ff75) "
error_symbol = "[❯ ](bold #E06C75) "

[cmd_duration]
min_time = 1
format = "[ $duration](#b8ff75) "

[directory]
format = "[ $path](#61AFEF) "
truncation_length = 3
truncation_symbol = "…/"

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](#E06C75)"

