# =====================================================================
# Nirmana-Shell - Transpiled Theme: froczh
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$dotnet\
$nodejs\
$status\
$fill\
$cmd_duration\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[character]
success_symbol = "[❯ ](bold #ffffff) "
error_symbol = "[❯ ](bold #ff0000) "

[os]
disabled = false
style = "fg:#ffffff bg:#40189c"
format = "[](fg:#40189c)[ $symbol ]($style)"

[os.symbols]
Windows = "󰕮"
Ubuntu = ""
Macos = ""
Linux = ""

[username]
format = "[ ](fg:#ffffff bg:#40189c)[ $user](fg:#ffffff bg:#40189c)"
show_always = true

[hostname]
format = "[@$hostname ](fg:#ffffff bg:#40189c)[](fg:#40189c)"
ssh_only = false

[directory]
format = "[](fg:#01579B inverted)[ $path ](fg:#ffffff bg:#01579B)[](fg:#01579B)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#00C853 inverted)[  $branch ](fg:#000000 bg:#00C853)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#000000 bg:#00C853))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[dotnet]
format = "[](fg:prev_bg bg:#00ffff)[ 󰪮 $version ](fg:#000000 bg:#00ffff)"

[nodejs]
format = "[](fg:prev_bg bg:#000000)[  $version ](fg:#45bf17 bg:#000000)"

[status]
format = "[](fg:prev_bg bg:#910000)[ $symbol ](fg:#ffffff bg:#910000)[](fg:#910000) "
disabled = false
symbol = "❌"
success_symbol = ""

[cmd_duration]
format = "[](fg:#29315A)[  $duration ](fg:#ffffff bg:#29315A)"
min_time = 2000

[time]
format = "[](fg:#29315A bg:prev_bg)[ $time ](fg:#3EC669 bg:#29315A)"
disabled = false
time_format = "%H:%M:%S | %A"
