# =====================================================================
# Nirmana-Shell - Transpiled Theme: hotstick.minimal
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character\
"""

[directory]
format = "[](fg:#80D8FF)[  $path ](fg:#000000 bg:#80D8FF)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#000000 bg:#69F0AE))[](fg:#69F0AE) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#80D8FF bg:#69F0AE)[  $branch](fg:#000000 bg:#69F0AE)"

[character]
success_symbol = ""
error_symbol = ""
