# =====================================================================
# Nirmana-Shell - Transpiled Theme: hul10
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$shell\
$username\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[shell]
format = "[  $version ](fg:#111111 bg:#f7f7f7)"

[username]
format = "[](fg:#f7f7f7 bg:#ffe093)[$user ](fg:#111111 bg:#ffe093)"
show_always = true

[git_status]
format = "([$all_status$ahead_behind ](fg:#111111 bg:#ffffd6))[](fg:#ffffd6) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#ffe093 bg:#ffffd6)[  $branch](fg:#111111 bg:#ffffd6)"

[cmd_duration]
format = "[  $duration ](fg:#b3ffde)"

[time]
format = "[  $time ](fg:#b3ffde)"
disabled = false
time_format = "%d/%m/%y %H:%M"

[character]
success_symbol = "[❯ ](bold #81ff91) "
error_symbol = "[❯ ](bold #ff3030) "
