# =====================================================================
# Nirmana-Shell - Transpiled Theme: hunk
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$nodejs\
$python\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$sudo\
$username\
$shell\
$line_break\
$sudo\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:#ffffff bg:#c44569)[](fg:#c44569) "
truncation_length = 3
truncation_symbol = "…/"

[nodejs]
symbol = "󰎙 "
format = "[󰎙 $version](fg:#ffffff bg:#f78fb3)[](fg:#f78fb3) "

[python]
symbol = "󰌠 "
format = "[󰌠 $version](fg:#ffffff bg:#f78fb3)[](fg:#f78fb3) "

[git_branch]
format = "[](fg:#caffbf)[ $branch](fg:#333333 bg:#caffbf)"

[git_status]
format = "([$all_status$ahead_behind](fg:#333333 bg:#caffbf)[](fg:#caffbf) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
min_time = 1
format = "[ $duration](fg:#ffffff bg:#83769c)[](fg:#83769c) "

[sudo]
disabled = false
symbol = " "
format = "[ ](yellow)"

[username]
show_always = true
format = "[](fg:#86BBD8)[ $user](fg:#ffffff bg:#86BBD8)[](fg:#86BBD8) "

[shell]
disabled = false
format = "[ $indicator](fg:#ffffff bg:#33658A)[](fg:#33658A) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
