# =====================================================================
# Nirmana-Shell - Transpiled Theme: huvix
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$golang\
$python\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[username]
format = "[$user](fg:#FFE082) "
show_always = true

[directory]
format = "[ $path](fg:#56B6C2) "
truncation_length = 3
truncation_symbol = "…/"

[golang]
format = "[ $version](fg:#7FD5EA) "

[python]
format = "[󰌠 $version](fg:#9e7eff) "

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#56B6C2) "

[cmd_duration]
format = "[ $duration](fg:#FFAB91) "
min_time = 1

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
