# =====================================================================
# Nirmana-Shell - Transpiled Theme: if_tea
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$memory_usage\
$cmd_duration\
$fill\
$git_branch\
$line_break\
$sudo\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[](fg:#ee79d1)[  $branch ](fg:#000000 bg:#ee79d1)"

[memory_usage]
format = "[ 󰍛 $ram_pct ](fg:#000000 bg:#00c7fc)"

[cmd_duration]
format = "[](fg:#00c7fc bg:#2343e2)[  $duration ](fg:#ffffff bg:#2343e2)[](fg:#2343e2) "
min_time = 1

[sudo]
disabled = false
symbol = " "
format = "[ ](yellow) "

[character]
success_symbol = "[╭─ ](bold #91f2ff) "
error_symbol = "[╭─ ](bold #ef5350) "
