# =====================================================================
# Nirmana-Shell - Transpiled Theme: illusi0n
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$memory_usage\
$line_break\
$character\
"""

[fill]
symbol = " "

[memory_usage]
disabled = false
threshold = 0
format = "[󰍛 $ram_pct](#ff8800) "

[character]
success_symbol = "[❯ ](bold #ff8800) "
error_symbol = "[❯ ](bold #ef5350) "

[username]
show_always = true
format = "[ ](#ff70a6)[$user](#ff8800) "

[directory]
format = "[ $path](#62c0ff) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $branch](#62c0ff)"

[git_status]
format = "([$all_status$ahead_behind](#62c0ff) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
