# =====================================================================
# Nirmana-Shell - Transpiled Theme: illusi0n
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$character\
$fill\
$memory_usage\
"""

[fill]
symbol = " "

[username]
format = "[$user](fg:#ff8800) "
show_always = true

[directory]
format = "[ $path](fg:#62c0ff) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#62c0ff) "

[memory_usage]
format = "[ 󰍛 $ram_pct ](fg:#ff8800)"

[character]
success_symbol = ""
error_symbol = ""
