# =====================================================================
# Nirmana-Shell - Transpiled Theme: iterm2
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$character\
$fill\
$battery\
$python\
$time\
$line_break\
$sudo\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[](fg:#003543)[ $user](fg:#d2ff5e bg:#003543)[](fg:#003543) "

[directory]
format = "[ $path](fg:#003544 bg:#0087D8)[](fg:#0087D8) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#d2ff5e)[ $branch](fg:#193549 bg:#d2ff5e)"

[git_status]
format = "([$all_status$ahead_behind](fg:#193549 bg:#d2ff5e)[](fg:#d2ff5e) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[character]
success_symbol = "[❯ ](bold #33DD2D) "
error_symbol = "[❯ ](bold #ef5350) "

[battery]
disabled = false
format = "[$symbol$percentage](fg:#242424 bg:#f36943)[](fg:#f36943) "

[python]
symbol = "󰌠 "
format = "[󰌠 $version](fg:#003544 bg:#0087D8)[](fg:#0087D8) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[$time](fg:#ffffff bg:#003543)[](fg:#003543) "

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](#FFD700)"
