# =====================================================================
# Nirmana-Shell - Transpiled Theme: jandedobbeleer-accessible
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$golang\
$julia\
$python\
$ruby\
$aws\
${env_var.ADMIN}\
$cmd_duration\
$status\
$character\
"""

[character]
success_symbol = "[❯ ](bold #22da6e) "
error_symbol = "[❯ ](bold #ef5350) "

[username]
format = "[](fg:#c386f1)[ $user ](fg:#ffffff bg:#c386f1)[](fg:#c386f1) "
show_always = true

[directory]
format = "[](fg:#ff479c)[ $path ](fg:#ffffff bg:#ff479c)[](fg:#ff479c) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#fffb38)[  $branch ](fg:#193549 bg:#fffb38)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#193549 bg:#fffb38))[](fg:#fffb38) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
format = "[](fg:#6CA35E)[ 󰎙 $version ](fg:#ffffff bg:#6CA35E)[](fg:#6CA35E) "

[golang]
format = "[](fg:#8ED1F7)[  $version ](fg:#111111 bg:#8ED1F7)[](fg:#8ED1F7) "

[julia]
format = "[](fg:#4063D8)[  $version ](fg:#111111 bg:#4063D8)[](fg:#4063D8) "

[python]
format = "[](fg:#FFDE57)[ 󰌠 $version ](fg:#111111 bg:#FFDE57)[](fg:#FFDE57) "

[ruby]
format = "[](fg:#AE1401)[  $version ](fg:#ffffff bg:#AE1401)[](fg:#AE1401) "

[aws]
format = "[](fg:#FFA400)[  $version ](fg:#ffffff bg:#FFA400)[](fg:#FFA400) "

[env_var.ADMIN]
variable = "STARSHIP_IS_ADMIN"
style = "fg:#111111 bg:#ffff66"
format = "[](fg:#ffff66)[ ⚡ ]($style)[](fg:#ffff66) "

[cmd_duration]
format = "[](fg:#83769c)[ $duration ](fg:#ffffff bg:#83769c)[](fg:#83769c) "
min_time = 0

[status]
format = "[](fg:#00897b)[ $status ](fg:#ffffff bg:#00897b)[](fg:#00897b) "

[shell]
format = "[  $indicator ](fg:#ffffff bg:#2e9599)"

[battery]
format = "[ 󰁹 $percentage ](fg:#ffffff bg:#2e9599)"
disabled = false

[[battery.display]]
threshold = 100
style = "bold #A6E3A1"

[time]
format = "[ $time ](fg:#111111 bg:#2e9599)"
disabled = false
time_format = "%H:%M:%S"
