# =====================================================================
# Nirmana-Shell - Transpiled Theme: jandedobbeleer
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$golang\
$julia\
$python\
$ruby\
$aws\
$sudo\
$cmd_duration\
$character\
"""

[character]
format = "[](fg:prev_bg) "
success_symbol = ""
error_symbol = ""

[username]
format = "[](fg:#c386f1)[ $user ](fg:#ffffff bg:#c386f1)[](fg:#c386f1)"
show_always = true

[directory]
format = "[](fg:#ff479c inverted)[ $path ](fg:#ffffff bg:#ff479c)[](fg:#ff479c) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#fffb38)[  $branch ](fg:#193549 bg:#fffb38)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#193549 bg:#fffb38))[](fg:#fffb38) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
format = "[](fg:prev_bg bg:#6CA35E)[  $version ](fg:#ffffff bg:#6CA35E)"

[golang]
format = "[](fg:prev_bg bg:#8ED1F7)[  $version ](fg:#111111 bg:#8ED1F7)"

[julia]
format = "[](fg:prev_bg bg:#4063D8)[  $version ](fg:#111111 bg:#4063D8)"

[python]
format = "[](fg:prev_bg bg:#FFDE57)[ 󰌠 $version ](fg:#111111 bg:#FFDE57)"
version_format = "${raw}"

[ruby]
format = "[](fg:prev_bg bg:#AE1401)[  $version ](fg:#ffffff bg:#AE1401)"

[aws]
format = "[](fg:prev_bg bg:#FFA400)[  $version ](fg:#ffffff bg:#FFA400)"

[sudo]
style = "fg:#111111 bg:#ffff66"
format = "[](fg:prev_bg bg:#ffff66)[ ⚡ ]($style)[](fg:#ffff66)"
disabled = false

[cmd_duration]
format = "[](fg:#83769c inverted)[  $duration ](fg:#ffffff bg:#83769c)"
min_time = 0
show_milliseconds = true

[shell]
format = "[](fg:#0077c2 bg:prev_bg)[  $indicator ](fg:#ffffff bg:#0077c2)"

[battery]
format = "[](fg:#f36943 bg:prev_bg)[ 󰁹 $percentage ](fg:#ffffff bg:#f36943)"
disabled = false

[[battery.display]]
threshold = 100
style = "bold #A6E3A1"

[time]
format = "[](fg:#2e9599 bg:prev_bg)[ $time ](fg:#111111 bg:#2e9599)[](fg:#2e9599)"
disabled = false
time_format = "%H:%M:%S"
