# =====================================================================
# Nirmana-Shell - Transpiled Theme: jandedobbeleer-accessible
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$golang\
$julia\
$python\
$ruby\
$aws\
$sudo\
$cmd_duration\
$fill\
$shell\
$battery\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[](fg:#c386f1)[ $user](fg:#ffffff bg:#c386f1)[](fg:#c386f1) "

[directory]
format = "[ $path](fg:#ffffff bg:#ff479c)[|](fg:#ff479c) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#fffb38)[ $branch](fg:#193549 bg:#fffb38)"

[git_status]
format = "([$all_status$ahead_behind](fg:#193549 bg:#fffb38)[|](fg:#fffb38) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = "󰎙 "
format = "[󰎙 $version](fg:#ffffff bg:#6CA35E)[|](fg:#6CA35E) "

[golang]
symbol = " "
format = "[ $version](fg:#111111 bg:#8ED1F7)[|](fg:#8ED1F7) "

[julia]
symbol = " "
format = "[ $version](fg:#111111 bg:#4063D8)[|](fg:#4063D8) "

[python]
symbol = "󰌠 "
format = "[󰌠 $version](fg:#111111 bg:#FFDE57)[|](fg:#FFDE57) "

[ruby]
symbol = " "
format = "[ $version](fg:#ffffff bg:#AE1401)[|](fg:#AE1401) "

[aws]
symbol = " "
format = "[ $version](fg:#ffffff bg:#FFA400)[|](fg:#FFA400) "

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](#111111)"

[cmd_duration]
min_time = 1
format = "[](fg:#83769c)[ $duration](fg:#ffffff bg:#83769c)[](fg:#83769c) "

[character]
success_symbol = "[❯ ](bold #00897b) "
error_symbol = "[❯ ](bold #ef5350) "

[shell]
disabled = false
format = "[](fg:#0077c2)[ $indicator](fg:#ffffff bg:#0077c2)[](fg:#0077c2) "

[battery]
disabled = false
format = "[$symbol$percentage](fg:#ffffff bg:#f36943)[|](fg:#f36943) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[|](fg:#2e9599)[$time](fg:#111111 bg:#2e9599) "
