# =====================================================================
# Nirmana-Shell - Transpiled Theme: jblab_2021
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$sudo\
$directory\
$git_branch\
$git_status\
$time\
$cmd_duration\
$character\
$line_break\
$character\
"""

[sudo]
disabled = false
symbol = " "
format = "[ ](#FFFFFF)"

[directory]
format = "[](bg:#26BDBB)[ $path](fg:#0C212F bg:#26BDBB) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#280C2E)[ $branch](fg:#FFFFFF bg:#280C2E)"

[git_status]
format = "([$all_status$ahead_behind](fg:#FFFFFF bg:#280C2E)[](fg:#280C2E) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[time]
disabled = false
time_format = "%H:%M"
format = "[](bg:#0C212F)[$time](fg:#FFFFFF bg:#0C212F) "

[cmd_duration]
min_time = 1
format = "[](bg:#26BDBB)[ $duration](fg:#0C212F bg:#26BDBB) "

[character]
success_symbol = "[❯ ](bold #ffffff) "
error_symbol = "[❯ ](bold #ef5350) "
