# =====================================================================
# Nirmana-Shell - Transpiled Theme: jblab_2021
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$os\
$sudo\
$directory\
$git_branch\
$git_status\
$time\
$cmd_duration\
$character\
"""

[character]
format = "$symbol"
success_symbol = ""
error_symbol = ""

[os]
disabled = false
style = "fg:#FFFFFF bg:#0C212F"
format = "[](fg:#0C212F)[ $symbol ]($style)[](fg:#0C212F)"

[os.symbols]
Windows = "󰕮"
Ubuntu = ""
Macos = ""
Linux = ""

[sudo]
style = "fg:#FFFFFF bg:#DE2121"
format = "[](fg:#DE2121 inverted)[  ]($style)[](fg:#DE2121)"
disabled = false

[directory]
format = "[](fg:#26BDBB inverted)[ $path ](fg:#0C212F bg:#26BDBB)[](fg:#26BDBB)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#280C2E inverted)[  $branch ](fg:#FFFFFF bg:#280C2E)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#FFFFFF bg:#280C2E))[](fg:#280C2E)"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[time]
format = "[](fg:#0C212F inverted)[ $time ](fg:#FFFFFF bg:#0C212F)[](fg:#0C212F)"
disabled = false
time_format = "%H:%M"

[cmd_duration]
format = "[](fg:#26BDBB inverted)[ $duration ](fg:#0C212F bg:#26BDBB)[](fg:#26BDBB) "
min_time = 0
show_milliseconds = true
