# =====================================================================
# Nirmana-Shell - Transpiled Theme: jonnychipz
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$username\
$line_break\
$sudo\
$character\
"""

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](purple) "

[username]
format = "[](fg:#4707a8)[$user ](fg:#ffffff bg:#4707a8)[](fg:#4707a8) "
show_always = true

[sudo]
disabled = false
symbol = " "
format = "[ ](#ffffff) "

[character]
success_symbol = "[❯ ](bold #000000) "
error_symbol = "[❯ ](bold #ef5350) "
