# =====================================================================
# Nirmana-Shell - Transpiled Theme: jonnychipz
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$character\
$line_break\
$sudo\
$directory\
$git_branch\
$git_status\
"""

[username]
show_always = true
format = "[$user](fg:#ffffff bg:#4707a8) "

[character]
success_symbol = "[ ](bold #ffffff) "
error_symbol = "[ ](bold #ef5350) "

[sudo]
disabled = false
symbol = " "
format = "[ ](#ffffff)"

[directory]
format = "[](fg:#ffffff)[ $path](fg:#000000 bg:#ffffff)[](fg:#ffffff) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#ffffff)[ $branch](fg:#000000 bg:#ffffff)"

[git_status]
format = "([$all_status$ahead_behind](fg:#000000 bg:#ffffff)[](fg:#ffffff) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
