# =====================================================================
# Nirmana-Shell - Transpiled Theme: jtracey93
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$status\
$line_break\
$character\
"""

[character]
success_symbol = "[❯ ](bold #ffffff) "
error_symbol = "[❯ ](bold #ff0000) "

[username]
format = "[](fg:#EB9654)[ $user ](fg:#ffffff bg:#EB9654)"
show_always = true

[directory]
format = "[ $path ](fg:#3f3f3f bg:#FFF59D)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[  $branch ](fg:#ffffff bg:#25AFF3)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#ffffff bg:#25AFF3))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
format = "[ $duration ](fg:#ffffff bg:#49404f)"
min_time = 0
show_milliseconds = true

[status]
format = "[ $symbol ](fg:#ffffff bg:#00897b)[](fg:#00897b) "
disabled = false
symbol = "❌"
success_symbol = "❌"
