# =====================================================================
# Nirmana-Shell - Transpiled Theme: kushal
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$os\
$shell\
${env_var.ADMIN}\
$python\
$golang\
$rust\
$git_branch\
$git_status\
$fill\
$status\
$cmd_duration\
$line_break\
[╭─](fg:#D6DEEB) \
$directory\
$line_break\
$character\
"""

[fill]
symbol = " "

[character]
success_symbol = "[❯ ](bold #D6DEEB) "
error_symbol = "[❯ ](bold #ef5350) "
format = "[╰─](fg:#D6DEEB)$symbol"

[os]
disabled = false
style = "fg:#D6DEEB bg:#575656"
format = "[](fg:#575656)[ $symbol ]($style)"

[os.symbols]
Windows = "󰕮"
Ubuntu = ""
Macos = ""
Linux = ""

[shell]
disabled = false
powershell_indicator = "pwsh"
bash_indicator = "bash"
zsh_indicator = "zsh"
style = "fg:#011627 bg:#00C7FC"
format = "[](fg:prev_bg bg:#00C7FC)[  $indicator ]($style)"

[env_var.ADMIN]
variable = "STARSHIP_IS_ADMIN"
style = "fg:#D6DEEB bg:#EF541C"
format = "[](fg:prev_bg bg:#EF541C)[ ⚡ ]($style)"

[python]
format = "[](fg:prev_bg bg:#FFDE57)[ 󰌠 ${virtualenv} $version ](fg:#011627 bg:#FFDE57)"
version_format = "${raw}"

[golang]
format = "[](fg:prev_bg bg:#7FD5EA)[  $version ](fg:#ffffff bg:#7FD5EA)"

[rust]
format = "[](fg:prev_bg bg:#99908A)[  $version ](fg:#193549 bg:#99908A)"

[git_branch]
format = "[](fg:prev_bg bg:#1BD4CD)[  $branch ](fg:#011627 bg:#1BD4CD)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#011627 bg:#1BD4CD))[](fg:#1BD4CD) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[status]
format = "[](fg:#03DED3 bg:prev_bg)[ $status ](fg:#414141 bg:#03DED3)"

[cmd_duration]
format = "[](fg:#575656 bg:prev_bg)[  $duration ](fg:#D6DEEB bg:#575656)"
min_time = 2000

[directory]
format = "[  ](bold #00C7FC)[ in ](bold #B6D6F2)[$path ](fg:#B6D6F2) "
truncation_length = 3
truncation_symbol = "…/"
