# =====================================================================
# Nirmana-Shell - Transpiled Theme: lambda
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character\
"""

[directory]
format = "[ $path](fg:#B80101) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#B80101) "

[character]
success_symbol = ""
error_symbol = ""
