# =====================================================================
# Nirmana-Shell - Transpiled Theme: lambdageneration
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$cmd_duration\
$directory\
$git_branch\
$git_status\
$battery\
$fill\
$username\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[cmd_duration]
format = "[╭─](fg:#292929)[  $duration ](fg:#fb7e14 bg:#292929)"
min_time = 1

[directory]
format = "[  $path ](fg:#fb7e14 bg:#292929)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#D4E157 bg:#292929))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[  $branch](fg:#D4E157 bg:#292929)"

[battery]
format = "[ 󰁹 $percentage ](fg:#26C6DA bg:#292929)[](fg:#292929) "

[username]
format = "[](fg:#292929)[ $user ](fg:#fb7e14 bg:#292929)"

[time]
format = "[  $time ](fg:#fb7e14 bg:#292929)"
disabled = false
time_format = "%H:%M:%S, _2"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
