# =====================================================================
# Nirmana-Shell - Transpiled Theme: lambdageneration
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$cmd_duration\
$sudo\
$directory\
$git_branch\
$git_status\
$battery\
$character\
$fill\
$username\
$time\
$line_break\
$directory\
"""

[fill]
symbol = " "

[cmd_duration]
min_time = 1
format = "[](fg:#292929)[ $duration](fg:#fb7e14 bg:#292929)[](fg:#292929) "

[sudo]
disabled = false
symbol = " "
format = "[ ](#26C6DA)"

[directory]
format = "[╰─](fg:#fb7e14)[ $path](fg:#292929 bg:#fb7e14)[](fg:#fb7e14) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#292929)[ $branch](fg:#D4E157 bg:#292929)"

[git_status]
format = "([$all_status$ahead_behind](fg:#D4E157 bg:#292929)[](fg:#292929) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[battery]
disabled = false
format = "[](fg:#292929)[$symbol$percentage](fg:#26C6DA bg:#292929)[](fg:#292929) "

[character]
success_symbol = "[❯ ](bold #292929) "
error_symbol = "[❯ ](bold #ef5350) "

[username]
show_always = true
format = "[](fg:#292929)[$user](fg:#fb7e14 bg:#292929) "

[time]
disabled = false
time_format = "%H:%M:%S, _2"
format = "[ $time](fg:#fb7e14 bg:#292929)[](fg:#292929) "
