# =====================================================================
# Nirmana-Shell - Transpiled Theme: lightgreen
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$sudo\
$directory\
$git_branch\
$git_status\
$python\
$golang\
$aws\
$fill\
$cmd_duration\
$memory_usage\
$battery\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](#dd1e1e)"

[directory]
format = "[](fg:#272727)[ $path](fg:#3EC669 bg:#272727)[](fg:#272727) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#272727)[ $branch](fg:#00ff0d bg:#272727)"

[git_status]
format = "([$all_status$ahead_behind](fg:#00ff0d bg:#272727)[](fg:#272727) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[python]
symbol = "󰌠 "
format = "[](fg:#306998)[󰌠 $version](fg:#FFE873 bg:#306998)[](fg:#306998)  "

[golang]
symbol = " "
format = "[](fg:#ffffff)[ $version](fg:#06aad5 bg:#ffffff)[](fg:#ffffff)  "

[aws]
symbol = " "
format = "[](fg:#565656)[ $version](fg:#faa029 bg:#565656)[](fg:#565656)  "

[cmd_duration]
min_time = 1
format = "[ $duration](yellow) "

[memory_usage]
disabled = false
threshold = 0
format = "[](fg:#ffffff)[󰍛 $ram_pct](fg:#3c3c3c bg:#ffffff)[](fg:#ffffff) "

[battery]
disabled = false
format = "[](fg:#f36943)[$symbol$percentage](fg:#262626 bg:#f36943) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[](fg:#000000)[ $time](fg:lightGreen bg:#000000)[](fg:#000000) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
