# =====================================================================
# Nirmana-Shell - Transpiled Theme: lightgreen
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$python\
$golang\
$character\
$fill\
$cmd_duration\
$memory_usage\
$battery\
$time\
"""

[fill]
symbol = " "

[directory]
format = "[](fg:#272727)[  $path ](fg:#3EC669 bg:#272727)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#00ff0d bg:#272727))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[  $branch](fg:#00ff0d bg:#272727)"

[python]
format = "[](fg:#272727 bg:#306998)[ 󰌠 $version ](fg:#FFE873 bg:#306998)"

[golang]
format = "[](fg:#306998 bg:#ffffff)[  $version ](fg:#06aad5 bg:#ffffff)[](fg:#ffffff) "

[cmd_duration]
format = "[  $duration ](fg:white)"

[memory_usage]
format = "[ 󰍛 $ram_pct ](fg:#3c3c3c bg:#ffffff)"

[battery]
format = "[](fg:#f36943 bg:#ffffff)[ 󰁹 $percentage ](fg:#262626 bg:#f36943)"
disabled = false

[time]
format = "[](fg:#000000 bg:#f36943)[  $time ](fg:#A5D6A7 bg:#000000)"
disabled = false
time_format = "%H:%M:%S"

[character]
success_symbol = ""
error_symbol = ""
