# =====================================================================
# Nirmana-Shell - Transpiled Theme: M365Princess
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$time\
$character\
"""

[username]
format = "[](fg:#9A348E)[$user ](fg:#FFFFFF bg:#9A348E)"
show_always = true

[directory]
format = "[](fg:#9A348E bg:#DA627D)[  $path ](fg:#FFFFFF bg:#DA627D)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#FFFFFF bg:#FCA17D))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#DA627D bg:#FCA17D)[  $branch](fg:#FFFFFF bg:#FCA17D)"

[nodejs]
format = "[](fg:#FCA17D bg:#86BBD8)[ 󰎙 $version ](fg:#FFFFFF bg:#86BBD8)"

[time]
format = "[](fg:#86BBD8 bg:#33658A)[  $time ](fg:#FFFFFF bg:#33658A)[](fg:#33658A) "
disabled = false
time_format = "%H:%M"

[character]
success_symbol = ""
error_symbol = ""
