# =====================================================================
# Nirmana-Shell - Transpiled Theme: M365Princess
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$time\
$line_break\
$character\
"""

[username]
show_always = true
format = "[$user](fg:p:white bg:p:plum) "

[directory]
format = "[](fg:p:blush)[ $path](fg:p:white bg:p:blush)[](fg:p:blush) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:p:salmon)[$branch](fg:p:white bg:p:salmon)"

[git_status]
format = "([$all_status$ahead_behind](fg:p:white bg:p:salmon)[](fg:p:salmon) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = "󰎙 "
format = "[](fg:p:sky)[󰎙 $version](fg:p:white bg:p:sky)[](fg:p:sky) "

[time]
disabled = false
time_format = "%H:%M"
format = "[$time](fg:p:white bg:p:teal_blue) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
