# =====================================================================
# Nirmana-Shell - Transpiled Theme: M365Princess
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$time\
$line_break\
$character\
"""

[username]
show_always = true
format = "[](fg:#9A348E)[$user](fg:#FFFFFF bg:#9A348E) "

[directory]
format = "[ $path](fg:#FFFFFF bg:#DA627D)[](fg:#DA627D) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#FCA17D)[ $branch](fg:#FFFFFF bg:#FCA17D)"

[git_status]
format = "([$all_status$ahead_behind](fg:#FFFFFF bg:#FCA17D)[](fg:#FCA17D) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = "󰎙 "
format = "[󰎙 $version](fg:#FFFFFF bg:#86BBD8)[](fg:#86BBD8) "

[time]
disabled = false
time_format = "%H:%M"
format = "[$time](fg:#FFFFFF bg:#33658A)[](fg:#33658A) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
