# =====================================================================
# Nirmana-Shell - Transpiled Theme: marcduiker
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character\
"""

[directory]
format = "[](fg:#feae34)[ $path](fg:#262b44 bg:#feae34)[](fg:#feae34) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#fee761)[ $branch](fg:#262b44 bg:#fee761)"

[git_status]
format = "([$all_status$ahead_behind](fg:#262b44 bg:#fee761)[](fg:#fee761) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[character]
success_symbol = "[⚡ ](bold #0095e9) "
error_symbol = "[⚡ ](bold #ef5350) "
