# =====================================================================
# Nirmana-Shell - Transpiled Theme: markbull
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[username]
format = "[$user ](fg:#1d1626 bg:#ffce7b)"
show_always = true

[directory]
format = "[](fg:#ffce7b bg:#C678DD)[  $path ](fg:#fffef9 bg:#C678DD)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#100e23 bg:#fffffb))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#C678DD bg:#fffffb)[  $branch](fg:#100e23 bg:#fffffb)"

[cmd_duration]
format = "[](fg:#fffffb bg:#33a3dc)[  $duration ](fg:#fffef9 bg:#33a3dc)[](fg:#33a3dc) "
min_time = 1

[character]
success_symbol = "[\\$ ](bold #ffffff) "
error_symbol = "[\\$ ](bold #ef5350) "
