# =====================================================================
# Nirmana-Shell - Transpiled Theme: material
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$time\
$character\
"""

[directory]
format = "[ $path](fg:#56B6C2) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#D0666F) "

[time]
format = "[ $time](fg:#66F68F) "
disabled = false
time_format = "%H:%M"

[character]
success_symbol = ""
error_symbol = ""
