# =====================================================================
# Nirmana-Shell - Transpiled Theme: mojada
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$sudo\
$directory\
$git_branch\
$git_status\
$fill\
$character\
$cmd_duration\
$battery\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[](fg:#fbfbfb)[ $user](fg:#0077c2 bg:#fbfbfb)[](fg:#fbfbfb) "

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](#ffffff)"

[directory]
format = "[ $path](fg:#ffffff bg:#0077c2)[](fg:#0077c2) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#fffb38)[ $branch](fg:#193549 bg:#fffb38)"

[git_status]
format = "([$all_status$ahead_behind](fg:#193549 bg:#fffb38)[](fg:#fffb38) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[character]
success_symbol = "[❯ ](bold #ffffff) "
error_symbol = "[❯ ](bold #ef5350) "

[cmd_duration]
min_time = 1
format = "[ $duration](#ffffff) "

[battery]
disabled = false
format = "[$symbol$percentage](fg:#ffffff bg:#f36943)[](fg:#f36943) "

[time]
disabled = false
time_format = "%H:%M (%a)"
format = "[$time](fg:#ffffff bg:#61afef)[](fg:#61afef) "
