# =====================================================================
# Nirmana-Shell - Transpiled Theme: mt
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[](fg:#B4009E)[$user](fg:#ffffff bg:#B4009E) "

[directory]
format = "[ $path](fg:#000000 bg:#FFFF00)[](fg:#FFFF00) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#4E44FF)[ $branch](fg:#ffffff bg:#4E44FF)"

[git_status]
format = "([$all_status$ahead_behind](fg:#ffffff bg:#4E44FF)[](fg:#4E44FF) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = "󰎙 "
format = "[󰎙 $version](fg:#ffffff bg:#4e903d)[](fg:#4e903d) "

[time]
disabled = false
time_format = "%H:%M"
format = "[ $time](fg:#ffffff bg:#16C60C)[](fg:#16C60C) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
