# =====================================================================
# Nirmana-Shell - Transpiled Theme: negligible
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$sudo\
$dart\
$nodejs\
$python\
$battery\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](cyan) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $branch](#F1502F)"

[git_status]
format = "([$all_status$ahead_behind](#F1502F) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](red)"

[dart]
symbol = " "
format = "[ $version](#06A4CE) "

[nodejs]
symbol = "󰎙 "
format = "[󰎙 $version](#6CA35E) "

[python]
symbol = "󰌠 "
format = "[󰌠 $version](#4584b6) "

[battery]
disabled = false
format = "[$symbol$percentage](#4caf50) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[ $time](lightGreen) "

[character]
success_symbol = "[❯ ](bold lightGreen) "
error_symbol = "[❯ ](bold #ef5350) "
