# =====================================================================
# Nirmana-Shell - Transpiled Theme: neko
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$time\
$character\
"""

[character]
success_symbol = "[😀💬 ~ ](bold #FF8000) "
error_symbol = "[😀💬 ~ ](bold #ef5350) "

[directory]
format = "[ $path ](bold #56B6C2)"

[git_branch]
format = "[  $branch ](bold #D0666F)"

[time]
format = "[ $time ](bold #1a415d)"
disabled = false
time_format = "%H:%M"
