# =====================================================================
# Nirmana-Shell - Transpiled Theme: nu4a
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$python\
$character\
"""

[character]
format = "$symbol"
success_symbol = "[](fg:prev_bg) "
error_symbol = "[](fg:prev_bg) "

[username]
format = "[ $user ](fg:#100e23 bg:#cfcfc4)"
show_always = true

[directory]
format = "[](fg:prev_bg bg:#ec9706)[ $path ](fg:#100e23 bg:#ec9706)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:prev_bg bg:#3feb56)[  $branch ](fg:#193549 bg:#3feb56)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#193549 bg:#3feb56))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[python]
format = "[](fg:prev_bg bg:#906cff)[ 󰌠 ${virtualenv} $version ](fg:#100e23 bg:#906cff)[](fg:#906cff) "
version_format = "${raw}"

[status]
format = "[](fg:#ff4040 bg:prev_bg)[ $status ](fg:#ffffff bg:#ff4040)"

[cmd_duration]
format = "[](fg:#2f2f2f bg:prev_bg)[ $duration ](fg:#fafafa bg:#2f2f2f)"
min_time = 2000
