# =====================================================================
# Nirmana-Shell - Transpiled Theme: patriksvensson
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$dotnet\
$line_break\
$character\
"""

[directory]
format = "[ $path](fg:#448AFF) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#69F0AE) "

[dotnet]
format = "[󰪮 $version](fg:#FF4081) "

[character]
success_symbol = "[❯ ](bold #69F0AE) "
error_symbol = "[❯ ](bold #ef5350) "
