# =====================================================================
# Nirmana-Shell - Transpiled Theme: plague
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$shell\
$character\
"""

[username]
format = "[](fg:#333333)[$user ](fg:#ff0000 bg:#333333)"
show_always = true

[directory]
format = "[](fg:#333333 bg:#ff0000)[  $path ](fg:#000000 bg:#ff0000)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#193549 bg:#fffb38))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#ff0000 bg:#fffb38)[  $branch](fg:#193549 bg:#fffb38)"

[nodejs]
format = "[](fg:#fffb38 bg:#6CA35E)[ 󰎙 $version ](fg:#ffffff bg:#6CA35E)"

[shell]
format = "[](fg:#6CA35E bg:#203248)[  $version ](fg:#ffffff bg:#203248)[](fg:#203248) "

[character]
success_symbol = ""
error_symbol = ""
