# =====================================================================
# Nirmana-Shell - Transpiled Theme: poshmon
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python\
$golang\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[](fg:#2e9599)[$user](fg:#ffffff bg:#2e9599)[](fg:#2e9599) "

[directory]
format = "[ $path](fg:#ffffff bg:#D51111)[](fg:#D51111) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#c19c00)[ $branch](fg:#000000 bg:#c19c00)"

[git_status]
format = "([$all_status$ahead_behind](fg:#000000 bg:#c19c00)[](fg:#c19c00) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = "󰎙 "
format = "[](fg:#303030)[󰎙 $version](fg:#3C873A bg:#303030)[](fg:#303030)  "

[python]
symbol = "󰌠 "
format = "[](fg:#306998)[󰌠 $version](fg:#FFE873 bg:#306998)[](fg:#306998)  "

[golang]
symbol = " "
format = "[](fg:#ffffff)[ $version](fg:#06aad5 bg:#ffffff)[](fg:#ffffff)  "

[time]
disabled = false
time_format = "_2, %H:%M:%S"
format = "[](fg:#2e9599)[ $time](fg:#ffffff bg:#2e9599)[](fg:#2e9599) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
