# =====================================================================
# Nirmana-Shell - Transpiled Theme: powerlevel10k_modern
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$os\
${env_var.ADMIN}\
$directory\
$git_branch\
$git_status\
$fill\
$python\
$golang\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[character]
success_symbol = "[❯ ](bold #D4E157) "
error_symbol = "[❯ ](bold #FF5252) "

[os]
disabled = false
style = "fg:#000000 bg:#ffffff"
format = "[](fg:#ffffff)[ $symbol ]($style)"

[os.symbols]
Windows = "󰕮"
Ubuntu = ""
Macos = ""
Linux = ""

[env_var.ADMIN]
variable = "STARSHIP_IS_ADMIN"
style = "fg:#000000 bg:#0000ff"
format = "[](fg:prev_bg bg:#0000ff)[ ⚡ ]($style)[](fg:#0000ff) "

[directory]
format = "[ ](fg:#ffffff bg:#0000ff)[ $path ](fg:#ffffff bg:#0000ff)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:prev_bg bg:#D4E157)[  $branch ](fg:#000000 bg:#D4E157)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#000000 bg:#D4E157))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[python]
format = "[](fg:#D4E157)[ 󰌠 $version ](fg:#000000 bg:#D4E157)[](fg:#D4E157) "

[golang]
format = "[](fg:#7FD5EA)[  $version ](fg:#ffffff bg:#7FD5EA)[](fg:#7FD5EA) "

[time]
format = "[](fg:#ffffff)[ $time ](fg:#000000 bg:#ffffff)[](fg:#ffffff) "
disabled = false
time_format = "%H:%M:%S"
