# =====================================================================
# Nirmana-Shell - Transpiled Theme: powerline
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$sudo\
$username\
$directory\
$git_branch\
$git_status\
$python\
$character\
$line_break\
$character\
"""

[sudo]
disabled = false
symbol = " "
format = "[ ](#FFEE58)"

[username]
show_always = true
format = "[ ](#ff70a6)[$user](#ffffff) "

[directory]
format = "[](fg:#91ddff)[ $path](fg:#100e23 bg:#91ddff)[](fg:#91ddff) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#95ffa4)[ $branch](fg:#193549 bg:#95ffa4)"

[git_status]
format = "([$all_status$ahead_behind](fg:#193549 bg:#95ffa4)[](fg:#95ffa4) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[python]
symbol = "󰌠 "
format = "[](fg:#906cff)[󰌠 $version](fg:#100e23 bg:#906cff)[](fg:#906cff) "

[character]
success_symbol = "[❯ ](bold #ffffff) "
error_symbol = "[❯ ](bold #ef5350) "
