# =====================================================================
# Nirmana-Shell - Transpiled Theme: pure
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[username]
format = "[$user](fg:#BF616A) "
show_always = true

[directory]
format = "[ $path](fg:#81A1C1) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#6C6C6C) "

[cmd_duration]
format = "[ $duration](fg:#A3BE8C) "
min_time = 1

[character]
success_symbol = "[❯ ](bold #B48EAD) "
error_symbol = "[❯ ](bold #BF616A) "
