# =====================================================================
# Nirmana-Shell - Transpiled Theme: quick-term
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
format = "[╭─](fg:#e4e4e4)[$user ](fg:#4e4e4e bg:#e4e4e4)"
show_always = true

[directory]
format = "[](fg:#e4e4e4 bg:#0087af)[  $path ](fg:#f2f3f8 bg:#0087af)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#f2f3f8 bg:#378504))[](fg:#378504) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#0087af bg:#378504)[  $branch](fg:#f2f3f8 bg:#378504)"

[cmd_duration]
format = "[](fg:#e4e4e4)[  $duration ](fg:#585858 bg:#e4e4e4)"

[time]
format = "[](fg:#d75f00 bg:#e4e4e4)[  $time ](fg:#f2f3f8 bg:#d75f00)"
disabled = false
time_format = "%H:%M:%S"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
