# =====================================================================
# Nirmana-Shell - Transpiled Theme: remk
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$time\
$line_break\
$character\
"""

[username]
show_always = true
format = "[$user](fg:#ffffff bg:lightMagenta) "

[directory]
format = "[](fg:lightYellow)[ $path](fg:#3f3f3f bg:lightYellow)[](fg:lightYellow) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:lightCyan)[$branch](fg:#ffffff bg:lightCyan)"

[git_status]
format = "([$all_status$ahead_behind](fg:#ffffff bg:lightCyan)[](fg:lightCyan) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[time]
disabled = false
time_format = "%H:%M"
format = "[$time](fg:#ffffff bg:lightGreen) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
