# =====================================================================
# Nirmana-Shell - Transpiled Theme: rudolfs-light
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
${env_var.ADMIN}\
$os\
$username\
$git_branch\
$git_status\
$directory\
$python\
$character\
"""

[character]
format = "$symbol"
success_symbol = ""
error_symbol = ""

[env_var.ADMIN]
variable = "STARSHIP_IS_ADMIN"
style = "fg:#BF231D bg:#E0E0E0"
format = "[ ⚡ ]($style)"

[os]
disabled = false
style = "fg:#EF7D00 bg:#E0E0E0"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = "󰕮"
Ubuntu = ""
Macos = ""
Linux = ""

[username]
format = "[ ](fg:#424242 bg:#E0E0E0)[ $user ](fg:#424242 bg:#E0E0E0)"
show_always = true

[git_branch]
format = "[  $branch ](fg:#424242 bg:#E0E0E0)"

[git_status]
format = "([$all_status$ahead_behind ](fg:#424242 bg:#E0E0E0))"
modified = " ~${count}"
staged = " +${count}"
stashed = " *${count}"
ahead = " ↑${count}"
behind = " ↓${count}"
diverged = " ↕↑${ahead_count}↓${behind_count}"
deleted = " -${count}"

[directory]
format = "[ ](fg:#424242 bg:#E0E0E0)[ $path ](fg:#424242 bg:#E0E0E0)"
truncation_length = 3
truncation_symbol = "…/"

[python]
format = "[ ](fg:#424242 bg:#E0E0E0)[ 󰌠 ${virtualenv} $version ](fg:#424242 bg:#E0E0E0)[](fg:#E0E0E0) "
version_format = "${raw}"
