# =====================================================================
# Nirmana-Shell - Transpiled Theme: rudolfs-dark
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$python\
$character\
"""

[username]
format = "[$user ](fg:#ffffff bg:#0A703E)"
show_always = true

[directory]
format = "[](fg:#0A703E bg:#256C9D)[  $path ](fg:#ffffff bg:#256C9D)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#ffffff bg:#256C9D))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[  $branch](fg:#ffffff bg:#256C9D)"

[python]
format = "[ 󰌠 $version ](fg:#ffffff bg:#256C9D)[](fg:#256C9D) "

[character]
success_symbol = ""
error_symbol = ""
