# =====================================================================
# Nirmana-Shell - Transpiled Theme: rudolfs-light
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$git_branch\
$git_status\
$directory\
$python\
$character\
"""

[username]
format = "[$user ](fg:#424242 bg:#E0E0E0)"
show_always = true

[git_status]
format = "([$all_status$ahead_behind ](fg:#424242 bg:#E0E0E0))"
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[  $branch](fg:#424242 bg:#E0E0E0)"

[directory]
format = "[  $path ](fg:#424242 bg:#E0E0E0)"
truncation_length = 3
truncation_symbol = "…/"

[python]
format = "[ 󰌠 $version ](fg:#424242 bg:#E0E0E0)[](fg:#E0E0E0) "

[character]
success_symbol = ""
error_symbol = ""
