# =====================================================================
# Nirmana-Shell - Transpiled Theme: sim-web
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$nodejs\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](purple) "

[cmd_duration]
format = "[  $duration ](fg:#a9ffb4)"

[nodejs]
format = "[ 󰎙 $version ](fg:#45bf17)"

[character]
success_symbol = "[❯_: ](bold #00c7fc) "
error_symbol = "[❯_: ](bold #ef5350) "
