# =====================================================================
# Nirmana-Shell - Transpiled Theme: slimfat
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python\
$dotnet\
$cmd_duration\
$time\
$line_break\
$sudo\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[](fg:#2f2f2f)[ $user](fg:#fafafa bg:#2f2f2f)[](fg:#2f2f2f) "

[sudo]
disabled = false
symbol = " "
format = "[ ](#ffff66) "

[directory]
format = "[](fg:#2f2f2f)[ $path](fg:#fafafa bg:#2f2f2f)[](fg:#2f2f2f) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#2f2f2f)[ $branch](fg:#ffeb3b bg:#2f2f2f)"

[git_status]
format = "([$all_status$ahead_behind](fg:#ffeb3b bg:#2f2f2f)[](fg:#2f2f2f) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
symbol = "󰎙 "
format = "[](fg:#2f2f2f)[󰎙 $version](fg:#6CA35E bg:#2f2f2f)[](fg:#2f2f2f) "

[python]
symbol = "󰌠 "
format = "[](fg:#2f2f2f)[󰌠 $version](fg:#96E072 bg:#2f2f2f)[](fg:#2f2f2f) "

[dotnet]
symbol = "󰪮 "
format = "[](fg:#2f2f2f)[󰪮 $version](fg:#3891A6 bg:#2f2f2f)[](fg:#2f2f2f) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[ $time](fg:#fafafa bg:#2f2f2f)[▓](fg:#2f2f2f) "

[character]
success_symbol = "[❯ ](bold #7a7a7a) "
error_symbol = "[❯ ](bold #9FD356) "

[cmd_duration]
min_time = 1
format = "[ $duration](#FFCE5C) "
