# =====================================================================
# Nirmana-Shell - Transpiled Theme: slimfat
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python\
$dotnet\
$time\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
format = "[▓](fg:#2f2f2f)[$user ](fg:#fafafa bg:#2f2f2f)"
show_always = true

[directory]
format = "[  $path ](fg:#fafafa bg:#2f2f2f)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#ffeb3b bg:#2f2f2f))[](fg:#2f2f2f) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[  $branch](fg:#ffeb3b bg:#2f2f2f)"

[nodejs]
format = "[](fg:#2f2f2f)[ 󰎙 $version ](fg:#6CA35E bg:#2f2f2f)"

[python]
format = "[ 󰌠 $version ](fg:#96E072 bg:#2f2f2f)"

[dotnet]
format = "[ 󰪮 $version ](fg:#3891A6 bg:#2f2f2f)"

[time]
format = "[  $time ](fg:#fafafa bg:#2f2f2f)"
disabled = false
time_format = "%H:%M:%S"

[cmd_duration]
format = "[  $duration ](fg:#FFCE5C)"

[character]
success_symbol = "[~#@❯ ](bold #7a7a7a) "
error_symbol = "[~#@❯ ](bold #ef5350) "
