# =====================================================================
# Nirmana-Shell - Transpiled Theme: smoothie
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$python\
$directory\
$git_branch\
$git_status\
$nodejs\
$fill\
$cmd_duration\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[python]
format = "[󰌠 $version](fg:#b1ff4f) "

[directory]
format = "[ $path](fg:#ffaed8) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#62beff) "

[nodejs]
format = "[󰎙 $version](fg:#98C379) "

[cmd_duration]
format = "[  $duration ](fg:#9966ff)"

[time]
format = "[  $time ](fg:#f5f5a6)"
disabled = false
time_format = "%H:%M:%S"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
