# =====================================================================
# Nirmana-Shell - Transpiled Theme: smoothie
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$python\
$directory\
$git_branch\
$git_status\
$nodejs\
$fill\
$status\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " "

[character]
success_symbol = "[❯ ](bold #22da6e) "
error_symbol = "[❯ ](bold #ef5350) "

[python]
format = "[󰌠 $version ](bold #b1ff4f) "

[directory]
format = "[$path ](fg:#ffaed8) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $branch](bold #62beff)"

[git_status]
format = "([$all_status$ahead_behind](bold #62beff)) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
format = "[󰎙 $version ](bold #98C379) "

[status]
format = "[ $status ](bold #fb0207)"

[cmd_duration]
format = "[ $duration ](bold #9966ff)"
min_time = 2000
