# =====================================================================
# Nirmana-Shell - Transpiled Theme: space
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$python\
$golang\
$nodejs\
$ruby\
$java\
$julia\
$character\
"""

[username]
format = "[$user](fg:#26C6DA) "
show_always = true

[directory]
format = "[ $path](fg:#A5D6A7) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](white) "

[python]
format = "[󰌠 $version](fg:#906cff) "

[golang]
format = "[ $version](fg:#7FD5EA) "

[nodejs]
format = "[󰎙 $version](fg:#76b367) "

[ruby]
format = "[ $version](fg:#f44336) "

[java]
format = "[ $version](fg:#ea2d2e) "

[julia]
format = "[ $version](fg:#4063D8) "

[character]
success_symbol = ""
error_symbol = ""
