# =====================================================================
# Nirmana-Shell - Transpiled Theme: space
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = false

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$golang\
$nodejs\
$julia\
$python\
$ruby\
$java\
$character\
"""

[character]
success_symbol = "[❯ ](bold #FFD54F) "
error_symbol = "[❯ ](bold #ef5350) "

[os]
disabled = false
style = "bold #26C6DA"
format = "[ $symbol ]($style) "

[os.symbols]
Windows = ""
Ubuntu = ""
Macos = ""
Linux = ""

[username]
format = "[$user ](bold #26C6DA)"
show_always = true

[directory]
format = "[$path ](fg:#A5D6A7) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[on ](fg:#ffffff)[ $branch](bold #addb67)"

[git_status]
format = "([$all_status$ahead_behind](bold #addb67)) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[golang]
format = "[ $version ](bold #7FD5EA) "

[nodejs]
format = "[ $version ](bold #76b367) "

[julia]
format = "[ $version ](bold #4063D8) "

[python]
format = "[ 󰌠 $version ](bold #906cff)"

[ruby]
format = "[  $version ](bold #f44336)"

[java]
format = "[  $version ](bold #ea2d2e)"
