# =====================================================================
# Nirmana-Shell - Transpiled Theme: star
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$line_break\
$character\
"""

[directory]
format = "[ $path](fg:#55B9C4) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#C678DD) "

[nodejs]
format = "[󰎙 $version](fg:#98C379) "

[character]
success_symbol = "[➜ ](bold #63F08C) "
error_symbol = "[➜ ](bold #ef5350) "
