# =====================================================================
# Nirmana-Shell - Transpiled Theme: stelbent-compact.minimal
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$time\
$line_break\
$character\
"""

[username]
format = "[$user](fg:#757575) "
show_always = true

[directory]
format = "[  $path ](fg:#100e23 bg:#91ddff)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind ](fg:#100e23 bg:#95ffa4))[](fg:#95ffa4) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[git_branch]
format = "[](fg:#91ddff bg:#95ffa4)[  $branch](fg:#100e23 bg:#95ffa4)"

[time]
format = "[ $time](fg:#689f38) "
disabled = false
time_format = "%H:%M:%S"

[character]
success_symbol = "[\\$ ](bold #ffffff) "
error_symbol = "[\\$ ](bold #ef5350) "
