# =====================================================================
# Nirmana-Shell - Transpiled Theme: the-unnamed
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$line_break\
$character\
"""

[directory]
format = "[ $path](fg:#15C2CB) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#F141A8) "

[nodejs]
format = "[󰎙 $version](fg:#44FFD2) "

[character]
success_symbol = "[❯ ](bold #FFE45E) "
error_symbol = "[❯ ](bold #ef5350) "
