# =====================================================================
# Nirmana-Shell - Transpiled Theme: tiwahu
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$sudo\
$character\
"""

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](purple) "

[sudo]
disabled = false
symbol = " "
format = "[ ](#2b2b2b) "

[character]
success_symbol = "[❯ ](bold #ff8888) "
error_symbol = "[❯ ](bold #ef5350) "
