# =====================================================================
# Tridatu-Shell — Tokyo Night Theme
# =====================================================================

scan_timeout = 30
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$php\
$nodejs\
$python\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #7AA2F7)"
error_symbol = "[❯](bold #F7768E)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold #2AC3DE"
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "bold #BB9AF7"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #E0AF68"
format = '([\[$all_status$ahead_behind\]]($style) )'

[cmd_duration]
min_time = 2_000
style = "bold #565F89"
format = "took [$duration]($style) "

[php]
symbol = " "
style = "bold #BB9AF7"
format = "[$symbol($version )]($style)"

[nodejs]
symbol = "󰎙 "
style = "bold #9ECE6A"
format = "[$symbol($version )]($style)"

[python]
symbol = "󰌠 "
style = "bold #E0AF68"
format = "[$symbol($version )]($style)"

[package]
disabled = true
[battery]
disabled = true
[dotnet]
disabled = true
[aws]
disabled = true
[gcloud]
disabled = true
[azure]
disabled = true
[docker_context]
disabled = true
