# =====================================================================
# Nirmana-Shell - Transpiled Theme: tokyo
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$time\
$username\
$memory_usage\
$battery\
$cmd_duration\
$line_break\
$sudo\
$character\
"""

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](purple) "

[time]
format = "[ $time](fg:#7eb8da) "
disabled = false
time_format = "%m/%d/%Y @ %I:%M:%S %p %Z"

[username]
format = "[$user](fg:#7eb8da) "
show_always = true

[memory_usage]
format = "[󰍛 $ram_pct](fg:#be9ddf) "

[battery]
format = "[󰁹 $percentage](fg:#f36943) "

[cmd_duration]
format = "[ $duration](fg:#be9ddf) "
min_time = 1

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](yellow) "

[character]
success_symbol = "[> ](bold green) "
error_symbol = "[> ](bold #ef5350) "
