# =====================================================================
# Nirmana-Shell - Transpiled Theme: tokyo
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$aws\
$memory_usage\
$battery\
$cmd_duration\
$time\
$line_break\
$sudo\
$character\
"""

[fill]
symbol = " "

[time]
disabled = false
time_format = "%m/%d/%Y @ %I:%M:%S %p %Z"
format = "[ $time](#7eb8da) "

[username]
show_always = true
format = "[ ](#ff70a6)[$user](#7eb8da) "

[memory_usage]
disabled = false
threshold = 0
format = "[󰍛 $ram_pct](#be9ddf) "

[battery]
disabled = false
format = "[$symbol$percentage](#f36943) "

[cmd_duration]
min_time = 1
format = "[ $duration](#be9ddf) "

[aws]
symbol = " "
format = "[ $version](#7eb8da) "

[directory]
format = "[ $path](#7eb8da) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $branch](#ffa5d8)"

[git_status]
format = "([$all_status$ahead_behind](#ffa5d8) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](yellow) "

[character]
success_symbol = "[❯ ](bold green) "
error_symbol = "[❯ ](bold #ef5350) "
