# =====================================================================
# Nirmana-Shell - Transpiled Theme: uew
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$username\
$git_branch\
$git_status\
$shell\
$fill\
$cmd_duration\
$time\
$nodejs\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[username]
format = "[$user](fg:#BBC4B9) "
show_always = true

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#BFA8BF) "

[shell]
format = "[ $version](fg:#BFA8BF) "

[cmd_duration]
format = "[  $duration ](fg:#ffffff)"

[time]
format = "[  $time ](fg:#BBC4B9)"
disabled = false
time_format = "%A at %I:%M %p"

[nodejs]
format = "[ 󰎙 $version ](fg:#BBC4B9)"

[character]
success_symbol = "[~ ](bold #BFA8BF) "
error_symbol = "[~ ](bold #fff) "
