# =====================================================================
# Nirmana-Shell - Transpiled Theme: uew
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$git_branch\
$git_status\
$shell\
$fill\
$cmd_duration\
$time\
$sudo\
$nodejs\
$line_break\
$directory\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[~](#BFA8BF) [$user](#BBC4B9) "

[git_branch]
format = "[ $branch](#BFA8BF)"

[git_status]
format = "([$all_status$ahead_behind](#BFA8BF) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[shell]
symbol = " "
format = "[ $indicator](#BFA8BF) "

[cmd_duration]
min_time = 1
format = "[ $duration](#fff) "

[time]
disabled = false
time_format = "%A <#fff>at %I:%M %p"
format = "[ $time](#BBC4B9) "

[sudo]
disabled = false
symbol = " "
format = "[ ](yellow)"

[nodejs]
symbol = "󰎙 "
format = "[󰎙 $indicator](#BBC4B9) "

[directory]
format = "[~](#BFA8BF)[ $path](#B6D6F2) "
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯ ](bold #BFA8BF) "
error_symbol = "[❯ ](bold #ef5350) "

