# =====================================================================
# Nirmana-Shell - Transpiled Theme: uew
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler v3.1
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$username\
$git_branch\
$git_status\
$shell\
$fill\
$cmd_duration\
$time\
${env_var.ADMIN}\
$nodejs\
$line_break\
$directory\
$character\
"""

[fill]
symbol = " "

[character]
success_symbol = "[~ ](bold #BFA8BF) "
error_symbol = "[~ ](bold #fff) "

[username]
format = "[~](bold #BFA8BF)[ ](bold #BBC4B9)[$user ](bold #BBC4B9)"
show_always = true

[git_branch]
format = "[on ](fg:#ffffff)[ $branch](bold #BFA8BF)"

[git_status]
format = "([$all_status$ahead_behind](bold #BFA8BF)) "
modified = " ✎"
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
format = "[ $duration ](bold #ffffff)"
min_time = 2000

[time]
format = "[ $time ](bold #BBC4B9)"
disabled = false
time_format = "%A at %I:%M %p"

[env_var.ADMIN]
format = "[   ](bold #ffeb95)"
variable = "STARSHIP_IS_ADMIN"

[nodejs]
format = "[  $version ](bold #BBC4B9)"

[directory]
format = "[~](bold #BFA8BF)[ $path ](fg:#B6D6F2) "
truncation_length = 3
truncation_symbol = "…/"
