# =====================================================================
# Nirmana-Shell - Transpiled Theme: unicorn
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$sudo\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:#003544 bg:#0087D8)[](fg:#0087D8) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#d2ff5e)[ $branch](fg:#193549 bg:#d2ff5e)"

[git_status]
format = "([$all_status$ahead_behind](fg:#193549 bg:#d2ff5e)[](fg:#d2ff5e) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[ $time](fg:#ffffff bg:#003543)[](fg:#003543) "

[cmd_duration]
min_time = 1
format = "[](fg:#83769c)[ $duration](fg:#ffffff bg:#83769c)[](fg:#83769c) "

[sudo]
disabled = false
symbol = "⚡ "
format = "[⚡ ](#ffffff) "

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
