# =====================================================================
# Nirmana-Shell - Transpiled Theme: velvet
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$character\
$fill\
$python\
$golang\
$nodejs\
$ruby\
$java\
$line_break\
$time\
"""

[fill]
symbol = " "

[directory]
format = "[](fg:#170B3B)[ $path](fg:#EFDCF9 bg:#170B3B)[](fg:#170B3B) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:#341948)[ $branch](fg:#EFDCF9 bg:#341948)"

[git_status]
format = "([$all_status$ahead_behind](fg:#EFDCF9 bg:#341948)[](fg:#341948) )"
modified = " "
staged = " "
stashed = " "
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
min_time = 1
format = "[](fg:#4c1f5e)[ $duration](fg:#EFDCF9 bg:#4c1f5e)[](fg:#4c1f5e) "

[character]
success_symbol = "[❯ ](bold #EFDCF9) "
error_symbol = "[❯ ](bold #FF3C3C) "

[python]
symbol = "󰌠 "
format = " [󰌠 $version](fg:#E4F34A bg:#4c1f5e) "

[golang]
symbol = " "
format = " [ $version](fg:#7FD5EA bg:#4c1f5e) "

[nodejs]
symbol = "󰎙 "
format = " [󰎙 $version](fg:#42E66C bg:#4c1f5e) "

[ruby]
symbol = " "
format = " [ $version](fg:#E64747 bg:#4c1f5e) "

[java]
symbol = " "
format = " [ $version](fg:#E64747 bg:#4c1f5e) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[$time](fg:#EFDCF9 bg:#4c1f5e) "
