# =====================================================================
# Nirmana-Shell - Transpiled Theme: wholespace
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$time\
$memory_usage\
$cmd_duration\
$fill\
$nodejs\
$git_branch\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:cyan) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[](fg:#17D7A0 bg:#ffffff)[  $branch ](fg:#011627 bg:#17D7A0)"

[time]
format = "[](fg:#FEF5ED)[  $time ](fg:#011627 bg:#FEF5ED)"
disabled = false
time_format = "%H:%M:%S"

[memory_usage]
format = "[ 󰍛 $ram_pct ](fg:#ffffff bg:#516BEB)"

[cmd_duration]
format = "[](fg:#516BEB bg:#575656)[  $duration ](fg:#d6deeb bg:#575656)[](fg:#575656) "
min_time = 1

[nodejs]
format = "[](fg:#ffffff)[ 󰎙 $version ](fg:#000000 bg:#ffffff)"

[character]
success_symbol = "[ ](bold #00ff15) "
error_symbol = "[ ](bold #ff0000) "
