# =====================================================================
# Nirmana-Shell - Transpiled Theme: wopian
# Ported from Oh My Posh JSON schema via Nirmana OMP Transpiler
# =====================================================================

scan_timeout = 30
command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$ruby\
$python\
$time\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
format = "[ $path](fg:#18FFFF) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
format = "([$all_status$ahead_behind](red) )"
modified = " ✎"
staged = " "

[git_branch]
format = "[ $branch](#FFF59D) "

[nodejs]
format = "[ 󰎙 $version ](fg:#68a063)"

[ruby]
format = "[  $version ](fg:#DE3F24)"

[python]
format = "[ 󰌠 $version ](fg:#FED142)"

[time]
format = "[  $time ](fg:#A5D6A7)"
disabled = false
time_format = "%H:%M:%S"

[character]
success_symbol = "[➜ ](bold #A5D6A7) "
error_symbol = "[➜ ](bold #ef5350) "
